# Cloud Build pipeline for MedFlow backend
# Builds and deploys all 6 services to Cloud Run in parallel.
#
# Trigger: push to main branch
# Usage:  gcloud builds submit --config cloudbuild.yaml .
# Manual: make cloud-submit-all
#
# Substitution variables:
#   _REGION     - Cloud Run region (default: europe-west1)
#   _REPOSITORY - Artifact Registry repo name (default: medflow)

substitutions:
  _REGION: europe-west1
  _REPOSITORY: medflow

timeout: 1800s # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/medflow-migrate-database-url/versions/latest
      env: DATABASE_URL

# ============================================================
# Step 1: Build all Docker images (parallel)
# ============================================================
steps:
  # --- Build ---
  - id: build-gateway
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api-gateway:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api-gateway:latest
      - -f
      - deployments/docker/Dockerfile.gateway
      - .
    waitFor: ['-']

  - id: build-auth
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/auth-service:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/auth-service:latest
      - -f
      - deployments/docker/Dockerfile.auth
      - .
    waitFor: ['-']

  - id: build-user
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/user-service:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/user-service:latest
      - -f
      - deployments/docker/Dockerfile.user
      - .
    waitFor: ['-']

  - id: build-staff
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/staff-service:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/staff-service:latest
      - -f
      - deployments/docker/Dockerfile.staff
      - .
    waitFor: ['-']

  - id: build-inventory
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/inventory-service:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/inventory-service:latest
      - -f
      - deployments/docker/Dockerfile.inventory
      - .
    waitFor: ['-']

  # ============================================================
  # Step 2: Run database migrations (must succeed before deploys)
  # Uses golang-migrate directly — requires pooler URL (IPv4) in
  # Secret Manager since Cloud Build lacks IPv6 support.
  # ============================================================
  - id: migrate
    name: alpine:3.19
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        apk add --no-cache curl ca-certificates
        curl -fsSL "https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz" | tar -xz -C /usr/local/bin/ migrate
        migrate -path migrations/supabase -database "$$DATABASE_URL" up
    secretEnv: [DATABASE_URL]
    waitFor: ['-']

  # ============================================================
  # Step 3: Push all images (after respective builds)
  # ============================================================
  - id: push-gateway
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api-gateway']
    waitFor: [build-gateway]

  - id: push-auth
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/auth-service']
    waitFor: [build-auth]

  - id: push-user
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/user-service']
    waitFor: [build-user]

  - id: push-staff
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/staff-service']
    waitFor: [build-staff]

  - id: push-inventory
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/inventory-service']
    waitFor: [build-inventory]

  # ============================================================
  # Step 4: Deploy all to Cloud Run (after pushes AND migration)
  # ============================================================
  - id: deploy-gateway
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - medflow-api-gateway
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api-gateway:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
    waitFor: [push-gateway, migrate]

  - id: deploy-auth
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - medflow-auth-service
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/auth-service:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
    waitFor: [push-auth, migrate]

  - id: deploy-user
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - medflow-user-service
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/user-service:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
    waitFor: [push-user, migrate]

  - id: deploy-staff
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - medflow-staff-service
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/staff-service:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
    waitFor: [push-staff, migrate]

  - id: deploy-inventory
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - medflow-inventory-service
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/inventory-service:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
    waitFor: [push-inventory, migrate]

# Push images to Artifact Registry
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api-gateway:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api-gateway:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/auth-service:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/auth-service:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/user-service:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/user-service:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/staff-service:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/staff-service:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/inventory-service:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/inventory-service:latest
